export default [
  {
    id: 'GOUVn9',
    name: "Ginger",
    breed: "Bombay",
    breedId: "bomb",
    age: "8 month",
    gender: "female",
    location: {
      lat: 48.146212,
      lng: 11.559204,
    },
    img: "https://www.zooplus.de/magazin/wp-content/uploads/2018/02/Bombay-Katze-Augen.jpg",
  },
  {
    id: 'ZGcXSc',
    name: "Gigi",
    breed: "Abyssinian",
    breedId: "abys",
    age: "2 years",
    gender: "Female",
    location: {
      lat: 48.137592,
      lng: 11.554269,
    },
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Gustav_chocolate.jpg/330px-Gustav_chocolate.jpg",
  },
  {
    id: 'CPmLq2',
    name: "Finnegan",
    breed: "American Shorthair",
    breedId: "asho",
    age: "1.7 years",
    gender: "male",
    location: {
      lat: 48.158115,
      lng: 11.522688,
    },
    img: "https://www.animalhouseshelter.com/wp-content/uploads/2023/08/spoons-head-0829a-600x600.jpg",
  },
  {
    id: 'XvW0Fk',
    name: "Finella",
    breed: "American Shorthair",
    breedId: "asho",
    age: "16 weeks",
    gender: "male",
    location: {
      lat: 48.162103,
      lng: 11.441056,
    },
    img: "https://www.animalhouseshelter.com/wp-content/uploads/2023/07/lullabye-head-0719a-600x600.jpg",
  },
  {
    id: 'grPNF7',
    name: "Fifi",
    breed: "Bombay",
    breedId: "bomb",
    age: "3 years",
    gender: "Female",
    location: {
      lat: 48.193929,
      lng: 11.567715,
    },
    img: "https://www.purina.co.uk/sites/default/files/styles/ttt_image_690/public/2021-01/Bombay.2.webp?itok=CLRaH02y",
  },
  {
    id: 'bkmga3',
    name: "Eden",
    breed: "Abyssinian",
    breedId: "abys",
    age: "2 years",
    gender: "Female",
    location: {
      lat: 48.111253,
      lng: 11.683684,
    },
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Valentino.jpg/375px-Valentino.jpg",
  },
  {
    id: 'j1FeUD',
    name: "Agatha",
    breed: "Bombay",
    breedId: "bomb",
    age: "18 weeks",
    gender: "Female",
    location: {
      lat: 48.130258,
      lng: 11.648935,
    },
    img: "https://www.animalhouseshelter.com/wp-content/uploads/2023/08/agatha-head-0817a-600x600.jpg",
  },
  {
    id: 'dJH2in',
    name: "Akito",
    breed: "Bombay",
    breedId: "bomb",
    age: "17 weeks",
    gender: "male",
    location: {
      lat: 48.152608,
      lng: 11.645167,
    },
    img: "https://www.animalhouseshelter.com/wp-content/uploads/2023/08/akito-head-0810b-600x600.jpg",
  },
  {
    id: 'Q4MNX1',
    name: "Angel",
    breed: "American Shorthair",
    breedId: "asho",
    age: "18 weeks",
    gender: "male",
    location: {
      lat: 48.150094,
      lng: 11.629676,
    },
    img: "https://www.animalhouseshelter.com/wp-content/uploads/2023/08/angel-head-0817a-600x600.jpg",
  },
  {
    id: 'JglqNa',
    name: "Antoinette",
    breed: "American Shorthair",
    breedId: "asho",
    age: "5 years",
    gender: "Female",
    location: {
      lat: 48.161824,
      lng: 11.581949,
    },
    img: "https://www.animalhouseshelter.com/wp-content/uploads/2020/01/antoinette-head-0320a-600x600.jpg",
  },
  {
    id: 'hWe2wA',
    name: "Arnie",
    breed: "American Shorthair",
    breedId: "asho",
    age: "1 year",
    gender: "male",
    location: {
      lat: 48.166742,
      lng: 11.576828,
    },
    img: "https://www.animalhouseshelter.com/wp-content/uploads/2023/08/arnie-head-0831a-600x600.jpg",
  },
  {
    id: 'NNZ8RT',
    name: "Auburn",
    breed: "American Shorthair",
    breedId: "asho",
    age: "1 year",
    gender: "male",
    location: {
      lat: 48.165376,
      lng: 11.541802,
    },
    img: "https://www.animalhouseshelter.com/wp-content/uploads/2021/03/auburn-head-1-768x768.jpg",
  },
  {
    id: 'ai5rFF',
    name: "Axil",
    breed: "American Shorthair",
    breedId: "asho",
    age: "6 years",
    gender: "Female",
    location: {
      lat: 48.176441,
      lng: 11.482605,
    },
    img: "https://www.animalhouseshelter.com/wp-content/uploads/2022/09/axil-head-0922a-600x600.jpg",
  },
  {
    id: 'l8xY0X',
    name: "Barbie",
    breed: "American Shorthair",
    breedId: "asho",
    age: "20 weeks",
    gender: "male",
    location: {
      lat: 48.158271,
      lng: 11.465194,
    },
    img: "https://www.animalhouseshelter.com/wp-content/uploads/2023/08/barbie-head-0825a-600x600.jpg",
  },
  {
    id: 'k1U5I8',
    name: "Bee Bee",
    breed: "American Shorthair",
    breedId: "asho",
    age: " 17 weeks",
    gender: "Female",
    location: {
      lat: 48.139642,
      lng: 11.495133,
    },
    img: "https://www.animalhouseshelter.com/wp-content/uploads/2019/08/beebee-head-0803a-600x600.jpg",
  },
  {
    id: 'aVZTFx',
    name: "Benji",
    breed: "American Shorthair",
    breedId: "asho",
    age: "2 years",
    gender: "Female",
    location: {
      lat: 48.120989,
      lng: 11.436266,
    },
    img: "https://www.animalhouseshelter.com/wp-content/uploads/2023/07/benji-head-0714a-600x600.jpg",
  },
  {
    id: 'c5Zg9k',
    name: "Boots",
    breed: "American Shorthair",
    breedId: "asho",
    age: "5 months",
    gender: "male",
    location: {
      lat: 48.093723,
      lng: 11.514307,
    },
    img: "https://www.animalhouseshelter.com/wp-content/uploads/2023/08/boots-head-0831a-600x600.jpg",
  },
  {
    id: 'ox26b2',
    name: "Carly",
    breed: "American Shorthair",
    breedId: "asho",
    age: "4 years",
    gender: "Female",
    location: {
      lat: 48.092857,
      lng: 11.50979,
    },
    img: "https://www.animalhouseshelter.com/wp-content/uploads/2023/08/carly-head-0809a-600x600.jpg",
  },
  {
    id: 'vD99rd',
    name: "Nilla",
    breed: "Nebelung",
    breedId: "nebe",
    age: "15 weeks",
    gender: "male",
    location: {
      lat: 48.101131,
      lng: 11.512779,
    },
    img: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/65697512/1/?bust=1690849317&width=1080",
  },
  {
    id: 'f2ANiu',
    name: "Chloe",
    breed: "Havana Brown",
    breedId: "hbro",
    age: "2 years",
    gender: "Female",
    location: {
      lat: 48.105938,
      lng: 11.483248,
    },
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Havana_Brown_-_choco.jpg/330px-Havana_Brown_-_choco.jpg",
  },
  {
    id: 'jyL5z1',
    name: "Celeste",
    breed: "Himalayan",
    breedId: "hima",
    age: "17 weeks",
    gender: "male",
    location: {
      lat: 48.113767,
      lng: 11.480538,
    },
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Himalayan_CAT.jpg/330px-Himalayan_CAT.jpg",
  },
  {
    id: 'LzPDZz',
    name: "Carrie Anne",
    breed: "Japanese Bobtail",
    breedId: "jbob",
    age: "18 weeks",
    gender: "Female",
    location: {
      lat: 48.140859,
      lng: 11.423927,
    },
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/JapaneseBobtailBlueEyedMi-ke.JPG/330px-JapaneseBobtailBlueEyedMi-ke.JPG",
  },
  {
    id: 'erhBBY',
    name: "Carmel",
    breed: "Himalayan",
    breedId: "hima",
    age: "2 yeras",
    gender: "Female",
    location: {
      lat: 48.154879,
      lng: 11.419414,
    },
    img: "https://upload.wikimedia.org/wikipedia/commons/e/ee/Himalayan_cat_percy.jpg",
  },
  {
    id: 'woJGjO',
    name: "Hazel",
    breed: "Japanese Bobtail",
    breedId: "jbob",
    age: "5 years",
    gender: "male",
    location: {
      lat: 48.160549,
      lng: 11.466847,
    },
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Japanese_bobtail_curled.jpg/330px-Japanese_bobtail_curled.jpg",
  },
  {
    id: 'mtW3kJ',
    name: "Ginger Snap",
    breed: "Bombay",
    breedId: "bomb",
    age: "17 weeks",
    gender: "male",
    location: {
      lat: 48.18749,
      lng: 11.450083,
    },
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Gata_com%C3%BAn_negra.png/330px-Gata_com%C3%BAn_negra.png",
  },
];
